[phases.setup]
NODE_VERSION = "20"
nixPkgs = ["chromium"]

[phases.install]
# ⚠️ Jangan jalankan npm install di sini!
# Cukup set skip download puppeteer
env = { PUPPETEER_SKIP_DOWNLOAD = "true" }

[phases.build]
# kosongkan saja
cmds = []

[start]
cmd = "node bot.js"
